-- /mnt/onboard/Ebooks/Ali Abdaal - Feel-Good Productivity_ How to Do More of What Matters to You.sdr/metadata.epub.lua
return {
    ["annotations"] = {
        [1] = {
            ["chapter"] = "Introduction",
            ["datetime"] = "2024-08-30 12:31:05",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[6]/body/section/p[22]/text().169",
            ["pageno"] = 14,
            ["pos0"] = "/body/DocFragment[6]/body/section/p[22]/text().169",
            ["pos1"] = "/body/DocFragment[6]/body/section/p[22]/text().328",
            ["text"] = "when we’re in a positive mood, we tend to consider a broader range of actions, be more open to new experiences, and better integrate the information we receive",
        },
        [2] = {
            ["chapter"] = "Introduction",
            ["datetime"] = "2024-08-30 12:31:27",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[6]/body/section/p[22]/text().346",
            ["pageno"] = 15,
            ["pos0"] = "/body/DocFragment[6]/body/section/p[22]/text().346",
            ["pos1"] = "/body/DocFragment[6]/body/section/p[22]/text().382",
            ["text"] = "feeling good boosts our creativity –",
        },
    },
    ["bookmarks"] = {},
    ["bookmarks_sorted_20220106"] = true,
    ["bookmarks_version"] = 20200615,
    ["cache_file_path"] = "./cache/cr3cache/Ali_Abdaal_--_to_You.epub.668027c9.1.cr3",
    ["config_panel_index"] = 4,
    ["copt_b_page_margin"] = 15,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 20,
    ["copt_h_page_margins"] = {
        [1] = 10,
        [2] = 10,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20210904,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 352,
    ["doc_path"] = "/mnt/onboard/Ebooks/Ali Abdaal - Feel-Good Productivity_ How to Do More of What Matters to You.epub",
    ["doc_props"] = {
        ["authors"] = "Abdaal, Ali",
        ["identifiers"] = "9781250865052",
        ["language"] = "en-US",
        ["title"] = "Feel-good Productivity : How to Do More of What Matters to You (9781250865052)",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Noto Serif",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["header_font_face"] = "Noto Sans",
    ["hide_nonlinear_flows"] = false,
    ["highlight"] = {},
    ["highlight_drawer"] = "lighten",
    ["highlights_imported"] = true,
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["last_xpointer"] = "/body/DocFragment[18]/body/section/p[44]/text().110",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "6567949969f0a697bcdadc922f2c6b32",
    ["partial_rerendering"] = true,
    ["percent_finished"] = 0.77556818181818,
    ["preferred_dictionaries"] = {},
    ["readermenu_tab_index"] = 7,
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "Abdaal, Ali",
        ["highlights"] = 94,
        ["language"] = "en-US",
        ["notes"] = 0,
        ["pages"] = 352,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "Feel-good Productivity : How to Do More of What Matters to You (9781250865052)",
    },
    ["summary"] = {
        ["modified"] = "2024-02-26",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-US",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
